variables:
  APP_DIR: /opt/docker/me-site
  IMAGE_TAG_SHA: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  IMAGE_TAG_COMMIT: $CI_REGISTRY_IMAGE:CI_COMMIT_TAG


stages:
  - build
  - deploy


.deploy_template:
  stage: deploy
  script:
    - ssh -o StrictHostKeyChecking=no  $DEPLOY_USER@$DEPLOY_HOST "
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      cd $APP_DIR &&
      IMAGE_NAME=$CI_REGISTRY_IMAGE IMAGE_TAG=$CI_COMMIT_SHORT_SHA docker compose pull &&
      IMAGE_NAME=$CI_REGISTRY_IMAGE IMAGE_TAG=$CI_COMMIT_SHORT_SHA docker compose up -d &&
      docker image prune -f
     "

build_job:
  stage: build

  # image: docker:latest
  # services: [docker:dind]

  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY


  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_TAG_SHA

    # Push для :git_тег (ЕСЛИ ЕСТЬ GIT ТЕГ)
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag $IMAGE_TAG_SHA $IMAGE_TAG_COMMIT
        docker push $IMAGE_TAG_COMMIT
      fi

    # Push :latest (ТОЛЬКО ОСНОВНАЯ ВЕТКА)
    - |
      if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
        docker tag $IMAGE_TAG_SHA $IMAGE_TAG_LATEST
        docker push $IMAGE_TAG_LATEST
      fi



deploy_stage:
  extends: .deploy_template
  environment:
    name: stage
    url: https://stage.dyuzha.ru
  variables:
    DEPLOY_HOST: $STAGE_HOST
    DEPLOY_USER: $STAGE_USER
  rules:
    - if: '$CI_COMMIT_BRANCH == "stage"'


deploy_prod:
  extends: .deploy_template
  environment:
    name: prod
    url: https://dyuzha.ru
  variables:
    DEPLOY_HOST: $PROD_HOST
    DEPLOY_USER: $PROD_USER
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
